defmodule Shazam.ConfigSync do
  @moduledoc "Generates IDE config files from shazam.yaml for Claude, Gemini, Cursor, Codex."

  use GenServer
  require Logger

  @providers ~w(claude gemini cursor codex)
  @header "<!-- Generated by Shazam. Do not edit manually. Run 'shazam sync' to regenerate. -->\n\n"
  @auto_sync_interval :timer.minutes(15)
  @max_memory_chars 2_000

  # --- GenServer for periodic auto-sync ---

  def start_link(opts \\ []) do
    GenServer.start_link(__MODULE__, opts, name: __MODULE__)
  end

  @impl true
  def init(_opts) do
    schedule_sync()
    {:ok, %{last_sync: nil}}
  end

  @impl true
  def handle_info(:auto_sync, state) do
    new_state = run_auto_sync(state)
    schedule_sync()
    {:noreply, new_state}
  end

  defp schedule_sync do
    Process.send_after(self(), :auto_sync, @auto_sync_interval)
  end

  defp run_auto_sync(state) do
    # Find all active companies and sync their workspaces
    try do
      companies = Registry.select(Shazam.CompanyRegistry, [{{:"$1", :_, :_}, [], [:"$1"]}])

      Enum.each(companies, fn company_name ->
        workspace = Application.get_env(:shazam, :workspace) || Shazam.Config.global_workspace()

        if workspace do
          {:ok, result} = sync(workspace, to_string(company_name))
          Logger.info("[ConfigSync] Auto-synced #{result.count} files for #{company_name}")
        end
      end)

      %{state | last_sync: DateTime.utc_now()}
    rescue
      e ->
        Logger.warning("[ConfigSync] Auto-sync error: #{Exception.message(e)}")
        state
    end
  end

  # --- Public API ---

  def sync(workspace, company_name, opts \\ []) do
    providers = Keyword.get(opts, :providers, @providers)
    preview = Keyword.get(opts, :preview, false)

    # Read directly from shazam.yaml — it's the source of truth for agent configs
    {agents, mission, tech_stack, skills, _domains, subagents} = read_from_yaml(workspace)

    # Fallback to Company GenServer if YAML not available
    {agents, mission} = if agents == [] do
      company_agents = try do
        Shazam.Company.get_agents_full(company_name)
      catch kind, reason ->
        Logger.debug("[ConfigSync] Failed to get agents: #{inspect(kind)}: #{inspect(reason)}")
        []
      end

      company_info = try do
        Shazam.Company.info(company_name)
      catch kind, reason ->
        Logger.debug("[ConfigSync] Failed to get company info: #{inspect(kind)}: #{inspect(reason)}")
        %{}
      end

      {company_agents, company_info[:mission] || ""}
    else
      {agents, mission}
    end

    memories = read_memories(workspace)

    results =
      Enum.flat_map(providers, fn provider ->
        case provider do
          "claude" ->
            Shazam.ConfigSync.ClaudeGenerator.generate(workspace, agents, skills, mission, tech_stack, memories, preview, subagents)

          "gemini" ->
            Shazam.ConfigSync.GeminiGenerator.generate(workspace, agents, skills, mission, tech_stack, memories, preview, subagents)

          "cursor" ->
            Shazam.ConfigSync.CursorGenerator.generate(workspace, agents, skills, mission, tech_stack, memories, preview, subagents)

          "codex" ->
            Shazam.ConfigSync.CodexGenerator.generate(workspace, agents, skills, mission, tech_stack, memories, preview, subagents)

          _ ->
            []
        end
      end)

    {:ok, %{files: results, count: length(results), providers: providers}}
  end

  def header, do: @header

  @doc "Check which generated config files exist in the workspace."
  def status(workspace) do
    files = [
      {"CLAUDE.md", "claude"},
      {"GEMINI.md", "gemini"},
      {"AGENTS.md", "codex"},
      {".claude/agents", "claude"},
      {".gemini/agents", "gemini"},
      {".cursor/agents", "cursor"}
    ]

    existing =
      Enum.filter(files, fn {path, _provider} ->
        full = Path.join(workspace, path)
        File.exists?(full)
      end)
      |> Enum.map(fn {path, provider} -> %{path: path, provider: provider} end)

    %{
      workspace: workspace,
      synced_files: existing,
      count: length(existing),
      last_sync: detect_last_sync(workspace)
    }
  end

  defp detect_last_sync(workspace) do
    claude_md = Path.join(workspace, "CLAUDE.md")

    if File.exists?(claude_md) do
      case File.stat(claude_md) do
        {:ok, stat} -> stat.mtime |> NaiveDateTime.from_erl!() |> NaiveDateTime.to_iso8601()
        _ -> nil
      end
    else
      nil
    end
  end

  @doc false
  def read_memories(workspace) do
    memories_dir = Path.join(workspace, ".shazam/memories")

    %{
      project: read_memory_dir(Path.join(memories_dir, "project")),
      rules: read_memory_dir(Path.join(memories_dir, "rules")),
      decisions: read_memory_dir(Path.join(memories_dir, "decisions")),
      agents: read_agent_memories(Path.join(memories_dir, "agents"))
    }
  end

  defp read_memory_dir(dir) do
    if File.dir?(dir) do
      dir
      |> File.ls!()
      |> Enum.filter(&String.ends_with?(&1, ".md"))
      |> Enum.reject(&(&1 == "SKILL.md"))
      |> Enum.map(fn file ->
        path = Path.join(dir, file)
        content = File.read!(path)

        body =
          case Regex.run(~r/\A---\n.*?\n---\n?(.*)/s, content) do
            [_, body] -> String.trim(body)
            _ -> String.trim(content)
          end

        body = truncate_memory(body)
        %{name: Path.basename(file, ".md"), content: body}
      end)
    else
      []
    end
  end

  defp read_agent_memories(dir) do
    if File.dir?(dir) do
      dir
      |> File.ls!()
      |> Enum.filter(&String.ends_with?(&1, ".md"))
      |> Enum.map(fn file ->
        path = Path.join(dir, file)
        agent_name = Path.basename(file, ".md")
        content = File.read!(path)

        body =
          case Regex.run(~r/\A---\n.*?\n---\n?(.*)/s, content) do
            [_, body] -> String.trim(body)
            _ -> String.trim(content)
          end

        body = truncate_memory(body)
        {agent_name, body}
      end)
      |> Map.new()
    else
      %{}
    end
  end

  defp truncate_memory(content) when byte_size(content) <= @max_memory_chars, do: content

  defp truncate_memory(content) do
    sliced = String.slice(content, 0, @max_memory_chars)

    case sliced |> String.split("\n") |> Enum.slice(0..-2//1) |> Enum.join("\n") do
      "" -> sliced <> "..."
      clean -> clean <> "\n..."
    end
  end

  @doc "Read agent config from shazam.yaml. Returns {agents, mission, tech_stack, skills, domains, subagents}."
  def read_from_yaml(workspace) do
    yaml_path = Path.join(workspace, ".shazam/shazam.yaml")
    alt_path = Path.join(workspace, "shazam.yaml")

    path = cond do
      File.exists?(yaml_path) -> yaml_path
      File.exists?(alt_path) -> alt_path
      true -> nil
    end

    if path do
      case YamlElixir.read_from_file(path) do
        {:ok, config} ->
          company = config["company"] || %{}
          mission = company["mission"] || ""
          tech_stack = config["tech_stack"] || %{}
          skills = (config["sync"] || %{})["skills"] || []
          domains = config["domains"] || %{}

          agents = (config["agents"] || %{})
            |> Enum.map(fn {name, data} ->
              %{
                name: name,
                role: data["role"] || "",
                supervisor: data["supervisor"],
                domain: data["domain"],
                model: data["model"],
                fallback_model: data["fallback_model"],
                provider: data["provider"],
                tools: data["tools"] || [],
                skills: data["skills"] || [],
                modules: data["modules"] || [],
                subagents: data["subagents"] || [],
                budget: data["budget"] || 0,
                heartbeat_interval: data["heartbeat_interval"] || 60_000,
                system_prompt: data["system_prompt"],
              }
            end)

          # Parse subagents from YAML (preset-based or custom)
          subagents_config = config["subagents"] || %{}
          subagents = subagents_config
            |> Enum.filter(fn {_name, cfg} -> is_nil(cfg) || cfg["enabled"] != false end)
            |> Enum.map(fn {name, cfg} ->
              cfg = cfg || %{}
              case Shazam.SubagentPresets.build(name, cfg) do
                {:ok, preset} -> preset
                {:error, _} ->
                  # Custom subagent (not a preset)
                  %{
                    name: name,
                    description: cfg["description"] || "Custom agent: #{name}",
                    default_model: cfg["model"] || "sonnet",
                    readonly: cfg["readonly"] || false,
                    tools: cfg["tools"] || ["Read", "Edit", "Write", "Bash", "Grep", "Glob"],
                    level: 2,
                    prompt: cfg["prompt"] || "You are #{name}."
                  }
              end
            end)

          {agents, mission, tech_stack, skills, domains, subagents}

        _ ->
          {[], "", %{}, [], %{}, []}
      end
    else
      {[], "", %{}, [], %{}, []}
    end
  end
end
