defmodule Shazam.ConfigImport do
  @moduledoc "Imports IDE config files (.claude/, .gemini/, .cursor/) and generates shazam.yaml"

  require Logger

  @doc """
  Scans workspace for existing IDE configs and generates a shazam.yaml.
  Returns {:ok, yaml_content} or {:error, reason}.
  """
  def import_from_workspace(workspace) do
    # Try each provider directory
    {claude_agents, claude_skills, claude_mission} = import_claude(workspace)
    {gemini_agents, _gemini_skills} = import_gemini(workspace)
    {cursor_agents, _cursor_skills} = import_cursor(workspace)
    codex_agents = import_codex(workspace)

    # Merge agents (Claude takes priority, then Gemini, then Cursor, then Codex)
    agents = merge_agents([claude_agents, gemini_agents, cursor_agents, codex_agents])
    skills = claude_skills  # Claude skills are the richest
    mission = claude_mission

    if agents == [] do
      {:error, :no_configs_found}
    else
      yaml = build_yaml(agents, skills, mission)
      {:ok, yaml}
    end
  end

  @doc "Import and write shazam.yaml to workspace"
  def import_and_save(workspace) do
    case import_from_workspace(workspace) do
      {:ok, yaml} ->
        dir = Path.join(workspace, ".shazam")
        File.mkdir_p!(dir)
        path = Path.join(dir, "shazam.yaml")
        File.write!(path, yaml)
        {:ok, path, yaml}

      error ->
        error
    end
  end

  # --- Claude Import ---

  defp import_claude(workspace) do
    agents_dir = Path.join(workspace, ".claude/agents")
    skills_dir = Path.join(workspace, ".claude/skills")
    commands_dir = Path.join(workspace, ".claude/commands")
    claude_md = Path.join(workspace, "CLAUDE.md")

    # Import agents
    agents =
      if File.dir?(agents_dir) do
        agents_dir
        |> File.ls!()
        |> Enum.filter(&String.ends_with?(&1, ".md"))
        |> Enum.map(fn file ->
          parse_agent_md(Path.join(agents_dir, file), "claude")
        end)
        |> Enum.reject(&is_nil/1)
        |> Enum.reject(fn a -> String.contains?(a.name || "", "Generated by Shazam") end)
      else
        []
      end

    # Import skills
    skills = import_skills_dir(skills_dir) ++ import_commands_dir(commands_dir)

    # Extract mission from CLAUDE.md
    mission =
      if File.exists?(claude_md) do
        content = File.read!(claude_md)
        extract_mission(content)
      else
        ""
      end

    {agents, skills, mission}
  end

  # --- Gemini Import ---

  defp import_gemini(workspace) do
    agents_dir = Path.join(workspace, ".gemini/agents")
    skills_dir = Path.join(workspace, ".gemini/skills")

    agents =
      if File.dir?(agents_dir) do
        agents_dir
        |> File.ls!()
        |> Enum.filter(&String.ends_with?(&1, ".md"))
        |> Enum.map(fn file -> parse_agent_md(Path.join(agents_dir, file), "gemini") end)
        |> Enum.reject(&is_nil/1)
      else
        []
      end

    skills = import_skills_dir(skills_dir)
    {agents, skills}
  end

  # --- Cursor Import ---

  defp import_cursor(workspace) do
    agents_dir = Path.join(workspace, ".cursor/agents")
    skills_dir = Path.join(workspace, ".agents/skills")

    agents =
      if File.dir?(agents_dir) do
        agents_dir
        |> File.ls!()
        |> Enum.filter(&String.ends_with?(&1, ".md"))
        |> Enum.map(fn file -> parse_agent_md(Path.join(agents_dir, file), "cursor") end)
        |> Enum.reject(&is_nil/1)
      else
        []
      end

    skills = import_skills_dir(skills_dir)
    {agents, skills}
  end

  # --- Codex Import ---

  defp import_codex(workspace) do
    agents_md = Path.join(workspace, "AGENTS.md")

    if File.exists?(agents_md) do
      content = File.read!(agents_md)
      parse_codex_agents(content)
    else
      []
    end
  end

  # --- Parsers ---

  defp parse_agent_md(path, provider) do
    content = File.read!(path)

    # Skip Shazam-generated files
    if String.contains?(content, "Generated by Shazam") do
      nil
    else
      case Regex.run(~r/\A---\n(.*?)\n---\n?(.*)/s, content) do
        [_, frontmatter, body] ->
          meta = parse_frontmatter(frontmatter)
          name = meta["name"] || Path.basename(path, ".md")

          # Map tools back to Shazam format
          tools =
            case provider do
              "gemini" -> map_gemini_tools_to_shazam(meta["tools"])
              _ -> parse_tools(meta["tools"])
            end

          # Map model back
          model = map_model_to_shazam(meta["model"], provider)

          %{
            name: name,
            role: meta["description"] || extract_role_from_body(body),
            model: model,
            tools: tools,
            system_prompt: String.trim(body),
            supervisor: extract_supervisor_from_body(body)
          }

        _ ->
          nil
      end
    end
  rescue
    _ -> nil
  end

  defp parse_frontmatter(text) do
    text
    |> String.split("\n")
    |> Enum.reduce(%{}, fn line, acc ->
      case String.split(line, ": ", parts: 2) do
        [key, value] ->
          value = String.trim(value) |> String.trim("\"")

          # Handle YAML arrays
          if String.starts_with?(value, "[") do
            items =
              value
              |> String.trim("[")
              |> String.trim("]")
              |> String.split(",")
              |> Enum.map(&String.trim/1)

            Map.put(acc, String.trim(key), items)
          else
            Map.put(acc, String.trim(key), value)
          end

        _ ->
          acc
      end
    end)
  end

  defp parse_tools(nil), do: []
  defp parse_tools(tools) when is_list(tools), do: tools

  defp parse_tools(tools) when is_binary(tools) do
    tools |> String.split(",") |> Enum.map(&String.trim/1) |> Enum.reject(&(&1 == ""))
  end

  defp map_gemini_tools_to_shazam(nil), do: []

  defp map_gemini_tools_to_shazam(tools) when is_list(tools) do
    mapping = %{
      "read_file" => "Read",
      "edit_file" => "Edit",
      "write_new_file" => "Write",
      "shell" => "Bash",
      "grep_search" => "Grep",
      "list_directory" => "Glob",
      "google_search" => "WebSearch"
    }

    Enum.map(tools, fn t -> mapping[String.trim(t)] || String.trim(t) end)
  end

  defp map_gemini_tools_to_shazam(_), do: []

  defp map_model_to_shazam(nil, _), do: nil
  defp map_model_to_shazam("inherit", _), do: nil
  defp map_model_to_shazam("fast", _), do: "claude-haiku-4-5-20251001"
  defp map_model_to_shazam("haiku", _), do: "claude-haiku-4-5-20251001"
  defp map_model_to_shazam("sonnet", _), do: nil
  defp map_model_to_shazam("opus", _), do: "claude-opus-4-6"
  defp map_model_to_shazam("gemini-2.0-flash" <> _, _), do: "claude-haiku-4-5-20251001"
  defp map_model_to_shazam("gemini-2.5-pro" <> _, _), do: nil
  defp map_model_to_shazam(model, _), do: model

  defp extract_role_from_body(body) do
    cond do
      String.contains?(body, "Project Manager") -> "Project Manager"
      String.contains?(body, "Senior Developer") -> "Senior Developer"
      String.contains?(body, "code reviewer") -> "Code Reviewer"
      String.contains?(body, "security") -> "Security Auditor"
      String.contains?(body, "QA") -> "QA Engineer"
      true -> "Developer"
    end
  end

  defp extract_supervisor_from_body(body) do
    case Regex.run(~r/Report(?:s)? to \*\*(\w+)\*\*/, body) do
      [_, supervisor] -> supervisor
      _ -> nil
    end
  end

  defp extract_mission(content) do
    cond do
      match = Regex.run(~r/# Project:\s*(.+)/, content) ->
        Enum.at(match, 1) |> String.trim()

      match = Regex.run(~r/# (.+)/, content) ->
        Enum.at(match, 1) |> String.trim()

      true ->
        ""
    end
  end

  defp import_skills_dir(dir) do
    if File.dir?(dir) do
      dir
      |> File.ls!()
      |> Enum.filter(fn entry -> File.dir?(Path.join(dir, entry)) end)
      |> Enum.map(fn skill_dir ->
        skill_md = Path.join([dir, skill_dir, "SKILL.md"])

        if File.exists?(skill_md) do
          content = File.read!(skill_md)

          case Regex.run(~r/\A---\n(.*?)\n---\n?(.*)/s, content) do
            [_, frontmatter, body] ->
              meta = parse_frontmatter(frontmatter)

              %{
                "name" => meta["name"] || skill_dir,
                "description" => meta["description"] || "",
                "prompt" => String.trim(body)
              }

            _ ->
              nil
          end
        else
          nil
        end
      end)
      |> Enum.reject(&is_nil/1)
    else
      []
    end
  end

  defp import_commands_dir(dir) do
    if File.dir?(dir) do
      dir
      |> File.ls!()
      |> Enum.filter(&String.ends_with?(&1, ".md"))
      |> Enum.map(fn file ->
        path = Path.join(dir, file)
        content = File.read!(path)
        name = Path.basename(file, ".md")

        case Regex.run(~r/\A---\n(.*?)\n---\n?(.*)/s, content) do
          [_, frontmatter, body] ->
            meta = parse_frontmatter(frontmatter)

            %{
              "name" => meta["name"] || name,
              "description" => meta["description"] || "",
              "prompt" => String.trim(body),
              "disable-model-invocation" => true
            }

          _ ->
            %{"name" => name, "description" => "", "prompt" => String.trim(content)}
        end
      end)
    else
      []
    end
  end

  defp parse_codex_agents(content) do
    # Parse sections like "### agent_name\n**Role**\n..."
    Regex.scan(~r/### (\w+)\s*\n\*\*([^*]+)\*\*/, content)
    |> Enum.map(fn [_, name, role] ->
      %{
        name: String.trim(name),
        role: String.trim(role),
        model: nil,
        tools: [],
        system_prompt: nil,
        supervisor: nil
      }
    end)
  end

  # --- Merge ---

  defp merge_agents(agent_lists) do
    # Flatten and deduplicate by name, first occurrence wins
    agent_lists
    |> List.flatten()
    |> Enum.reduce(%{}, fn agent, acc ->
      if Map.has_key?(acc, agent.name) do
        acc
      else
        Map.put(acc, agent.name, agent)
      end
    end)
    |> Map.values()
    |> Enum.sort_by(fn a -> if a.supervisor == nil, do: "0_#{a.name}", else: "1_#{a.name}" end)
  end

  # --- YAML Generation ---

  defp build_yaml(agents, skills, mission) do
    company_name = mission |> String.split(~r/[\s\x{2014}\-]/u) |> List.first() || "MyProject"

    agents_yaml =
      agents
      |> Enum.map(fn a ->
        lines = ["  #{a.name}:"]
        lines = lines ++ ["    role: #{a.role}"]
        lines = if a.supervisor, do: lines ++ ["    supervisor: #{a.supervisor}"], else: lines
        lines = if a.model, do: lines ++ ["    model: #{a.model}"], else: lines

        lines =
          if a.tools != [] do
            tools_str = Enum.map_join(a.tools, "\n", fn t -> "      - #{t}" end)
            lines ++ ["    tools:\n#{tools_str}"]
          else
            lines
          end

        lines =
          if a.system_prompt && a.system_prompt != "" do
            # Truncate long prompts
            prompt = String.slice(a.system_prompt, 0..200)
            lines ++ ["    system_prompt: |", "      #{prompt}"]
          else
            lines
          end

        Enum.join(lines, "\n")
      end)
      |> Enum.join("\n\n")

    skills_yaml =
      if skills != [] do
        skill_entries =
          skills
          |> Enum.map(fn s ->
            lines = ["    - name: #{s["name"]}"]
            lines = lines ++ ["      description: #{s["description"]}"]

            lines =
              if s["prompt"] && s["prompt"] != "" do
                prompt = String.slice(s["prompt"], 0..100)
                lines ++ ["      prompt: |", "        #{prompt}"]
              else
                lines
              end

            Enum.join(lines, "\n")
          end)
          |> Enum.join("\n")

        """

        sync:
          providers: [claude, gemini, cursor, codex]
          skills:
        #{skill_entries}
        """
      else
        ""
      end

    """
    # Generated by shazam import
    # Review and customize this file, then run: shazam sync

    company:
      name: #{company_name}
      mission: #{mission}

    agents:
    #{agents_yaml}
    #{skills_yaml}
    config:
      auto_approve: false
      max_concurrent: 4
      max_retries: 2
      poll_interval: 5000
    """
  end
end
