defmodule Shazam.ConfigSync.ClaudeGenerator do
  @moduledoc "Generates .claude/agents/*.md, .claude/skills/*, and CLAUDE.md"

  # No longer generating per-agent files — Shazam agents are daemon-managed.
  # Only namespaced subagent files ({agent}--{subagent}.md) are generated.

  def generate(workspace, agents, skills, mission, tech_stack, memories \\ %{}, preview \\ false, subagents \\ []) do
    files = []

    # Generate CLAUDE.md (with team info + subagent references)
    claude_md = build_claude_md(agents, mission, tech_stack, memories, subagents)
    files = files ++ [%{path: Path.join(workspace, "CLAUDE.md"), content: claude_md, type: "context"}]

    # DO NOT generate agent files for Shazam agents (pm, senior_1, etc.)
    # They are daemon-managed, not Claude Code subagents.

    # Generate namespaced subagent files: {agent}--{subagent}.md
    subagent_files =
      agents
      |> Enum.flat_map(fn agent ->
        name = agent_name(agent)
        agent_subs = agent_subagents(agent)

        Enum.map(agent_subs, fn sub_name ->
          preset = Enum.find(subagents, fn sa -> sa.name == sub_name end)

          if preset do
            filename = "#{name}--#{sub_name}.md"
            content = build_namespaced_subagent_md(agent, preset, mission)
            %{path: Path.join(workspace, ".claude/agents/#{filename}"), content: content, type: "subagent"}
          end
        end)
        |> Enum.reject(&is_nil/1)
      end)

    files = files ++ subagent_files

    # Generate skill files
    skill_files =
      Enum.map(skills, fn skill ->
        content = build_skill_md(skill)
        name = skill["name"] || "unnamed"
        %{path: Path.join(workspace, ".claude/skills/#{name}/SKILL.md"), content: content, type: "skill"}
      end)

    files = files ++ skill_files

    # Generate .claude/settings.json (only if it doesn't exist — don't overwrite user config)
    settings_path = Path.join(workspace, ".claude/settings.json")
    settings_file = if !File.exists?(settings_path) do
      settings_content = build_settings_json(agents)
      [%{path: settings_path, content: settings_content, type: "settings"}]
    else
      []
    end

    files = files ++ settings_file

    # Generate .claude/rules/shazam-project.md (only if it doesn't exist)
    rules_path = Path.join(workspace, ".claude/rules/shazam-project.md")
    rules_file = if !File.exists?(rules_path) do
      rules_content = build_rules_md(agents, mission)
      [%{path: rules_path, content: rules_content, type: "rules"}]
    else
      []
    end

    files = files ++ rules_file

    unless preview do
      Enum.each(files, fn file ->
        File.mkdir_p!(Path.dirname(file.path))
        # Only write if file doesn't exist or was generated by Shazam
        should_write = !File.exists?(file.path) ||
          (File.read!(file.path) |> String.contains?("Generated by Shazam"))
        if should_write do
          File.write!(file.path, file.content)
        end
      end)

      # Create agent-memory directories for each subagent
      agents
      |> Enum.each(fn agent ->
        name = agent_name(agent)
        subs = agent_subagents(agent) || []
        Enum.each(subs, fn sub ->
          memory_dir = Path.join(workspace, ".claude/agent-memory/#{name}--#{sub}")
          File.mkdir_p!(memory_dir)
          memory_md = Path.join(memory_dir, "MEMORY.md")
          unless File.exists?(memory_md) do
            File.write!(memory_md, "")
          end
        end)
      end)

      # Clean up orphaned files (old agent files + old subagent files)
      cleanup_orphaned_files(workspace, agents)
    end

    files
  end

  defp cleanup_orphaned_files(workspace, agents) do
    agents_dir = Path.join(workspace, ".claude/agents")
    if File.dir?(agents_dir) do
      # Build set of expected filenames: {agent}--{subagent}.md
      expected =
        agents
        |> Enum.flat_map(fn agent ->
          name = agent_name(agent)
          subs = agent_subagents(agent)
          Enum.map(subs, fn sub -> "#{name}--#{sub}.md" end)
        end)
        |> MapSet.new()

      # Remove files generated by Shazam that are no longer expected
      agents_dir
      |> File.ls!()
      |> Enum.filter(&String.ends_with?(&1, ".md"))
      |> Enum.each(fn file ->
        unless MapSet.member?(expected, file) do
          path = Path.join(agents_dir, file)
          if File.read!(path) |> String.contains?("Generated by Shazam") do
            File.rm!(path)
          end
        end
      end)
    end
  end

  defp build_settings_json(agents) do
    all_tools =
      agents
      |> Enum.flat_map(fn agent ->
        tools = agent_tools(agent)
        if is_list(tools), do: tools, else: []
      end)
      |> Enum.uniq()
      |> Enum.sort()
      |> Enum.map(fn tool ->
        if tool == "Bash", do: "Bash(*)", else: tool
      end)

    tools_json = Enum.map_join(all_tools, ",\n      ", fn t -> "\"#{t}\"" end)

    """
    {
      "permissions": {
        "allow": [
          #{tools_json}
        ]
      }
    }
    """
    |> String.trim_trailing()
    |> Kernel.<>("\n")
  end

  defp build_rules_md(agents, mission) do
    agent_count = length(agents)
    mission_str = if mission && mission != "", do: mission, else: "Project"

    """
    <!-- Generated by Shazam. Do not edit manually. -->

    # Project Rules — #{mission_str}

    ## Code Style
    - Follow existing patterns and conventions in the codebase
    - Keep changes focused and minimal
    - Write self-documenting code with clear naming

    ## Testing
    - Write tests for new features
    - Run existing tests before committing
    - Don't skip failing tests — fix them

    ## Git
    - Write clear commit messages describing the "why"
    - Keep commits focused on a single concern

    ## Agent Coordination
    - This project uses Shazam with #{agent_count} agents
    - Respect module boundaries — don't edit files owned by other agents
    - Report blockers to the PM agent
    """
  end

  defp build_claude_md(agents, mission, tech_stack, memories, _all_subagents) do
    header = Shazam.ConfigSync.header()

    mission_section =
      if mission && mission != "" do
        "# #{mission}\n\n## Project Overview\nThis project uses a managed agent team coordinated by Shazam.\n"
      else
        "# Project\n"
      end

    tech_section =
      if tech_stack && tech_stack != %{} do
        items = Enum.map_join(tech_stack, "\n", fn {k, v} -> "- **#{k}**: #{v}" end)
        "\n## Tech Stack\n#{items}\n"
      else
        ""
      end

    # Team & Subagents section (replaces old Team section)
    team_subagents_section =
      if length(agents) > 0 do
        pms = Enum.count(agents, fn a -> is_pm?(a) end)
        devs = Enum.count(agents, fn a -> !is_pm?(a) end)

        team_summary =
          cond do
            pms > 0 && devs > 0 ->
              "This project uses a managed agent team with #{pms} PM and #{devs} developers."

            devs > 0 ->
              "This project uses a team of #{devs} developers."

            true ->
              "This project uses a managed agent team."
          end

        agent_entries =
          Enum.map_join(agents, "\n\n", fn a ->
            name = agent_name(a)
            role = agent_role(a)
            sup = agent_supervisor(a)
            supervisor = if sup, do: " (reports to #{sup})", else: " (top-level)"
            subs = agent_subagents(a)

            subagent_line =
              if is_list(subs) && length(subs) > 0 do
                sub_refs = Enum.map_join(subs, ", ", fn s -> "@#{name}--#{s}" end)
                "\nSubagents: #{sub_refs}"
              else
                ""
              end

            "### #{name} (#{role})#{supervisor}#{subagent_line}"
          end)

        has_any_subs = Enum.any?(agents, fn a ->
          subs = agent_subagents(a)
          is_list(subs) && length(subs) > 0
        end)

        instruction = if has_any_subs do
          """

          **IMPORTANT: Always use available subagents when their specialty matches the task.**
          Delegate to subagents proactively — they run in isolated context with specialized prompts.
          Use `@agent--subagent` to invoke them (e.g., `@pm--planner`, `@senior_1--executor`).
          """
        else
          ""
        end

        "\n## Team & Subagents\n#{team_summary}\n#{instruction}\n#{agent_entries}\n"
      else
        ""
      end

    # Domains from agent modules
    domains_section = build_domains_section(agents)

    # Project memories
    memories_section = build_memories_section(memories[:project], "Project Knowledge")
    rules_section = build_memories_section(memories[:rules], "Rules")
    decisions_section = build_memories_section(memories[:decisions], "Decisions")

    """
    #{header}#{mission_section}#{tech_section}#{team_subagents_section}#{domains_section}#{memories_section}#{rules_section}#{decisions_section}
    ## Guidelines
    - Follow existing code patterns and conventions
    - Write tests for new features
    - Keep changes focused and minimal
    - Report issues to the PM agent
    """
  end

  defp build_memories_section(nil, _title), do: ""
  defp build_memories_section([], _title), do: ""

  defp build_memories_section(memories, title) do
    content =
      Enum.map_join(memories, "\n\n", fn m ->
        "### #{String.capitalize(m.name)}\n#{m.content}"
      end)

    "\n## #{title}\n#{content}\n"
  end

  defp build_domains_section(agents) do
    domains =
      agents
      |> Enum.flat_map(fn a ->
        domain = agent_domain(a)
        if domain && domain != "", do: [domain], else: []
      end)
      |> Enum.uniq()

    if length(domains) > 0 do
      items = Enum.map_join(domains, "\n", fn d -> "- **#{d}**" end)
      "\n## Domains\n#{items}\n"
    else
      ""
    end
  end

  defp build_namespaced_subagent_md(parent_agent, preset, mission) do
    header = Shazam.ConfigSync.header()
    parent_name = agent_name(parent_agent)
    parent_role = agent_role(parent_agent)
    sub_name = preset.name
    sub_desc = preset.description || ""
    sub_model = Shazam.ModelProxy.resolve("claude", preset.default_model || "sonnet")
    sub_prompt = preset.prompt || ""
    is_readonly = preset.readonly || false

    full_name = "#{parent_name}--#{sub_name}"

    # Build description with usage examples (escaped newlines for YAML single-line)
    description_with_examples =
      "#{sub_desc}. Use when #{parent_name} (#{parent_role}) needs #{sub_name} capabilities." <>
      "\\n\\nExamples:\\n\\n" <>
      "- User: \\\"Help me with #{sub_name} tasks\\\"\\n" <>
      "  Assistant: \\\"I'll use the Agent tool to launch #{full_name}.\\\""

    tools_section =
      if is_readonly do
        "disallowedTools: Write, Edit\n"
      else
        ""
      end

    """
    ---
    name: "#{full_name}"
    description: "#{description_with_examples}"
    model: #{sub_model}
    memory: project
    #{tools_section}---

    #{String.trim(header)}

    You are **#{sub_name}**, a specialized subagent of **#{parent_name}** (#{parent_role}) in the **#{mission}** project.

    ## Your Role
    #{String.trim(sub_desc)}

    #{String.trim(sub_prompt)}
    """
  end

  defp build_skill_md(skill) do
    header = Shazam.ConfigSync.header()
    name = skill["name"] || "unnamed"
    description = skill["description"] || ""
    prompt = skill["prompt"] || ""

    """
    #{header}---
    name: "#{name}"
    description: "#{description}"
    ---

    #{prompt}
    """
  end

  # --- Helpers ---

  defp is_pm?(agent) do
    role = agent_role(agent)
    String.contains?(String.downcase(role), "manager")
  end

  # Access helpers that work with both structs and maps
  defp agent_name(%{name: n}), do: n
  defp agent_name(%{"name" => n}), do: n
  defp agent_name(_), do: "unnamed"

  defp agent_role(%{role: r}), do: r
  defp agent_role(%{"role" => r}), do: r
  defp agent_role(_), do: ""

  defp agent_supervisor(%{supervisor: s}), do: s
  defp agent_supervisor(%{"supervisor" => s}), do: s
  defp agent_supervisor(_), do: nil

  defp agent_tools(%{tools: t}), do: t
  defp agent_tools(%{"tools" => t}), do: t
  defp agent_tools(_), do: []

  defp agent_domain(%{domain: d}), do: d
  defp agent_domain(%{"domain" => d}), do: d
  defp agent_domain(_), do: nil

  defp agent_subagents(%{subagents: s}) when is_list(s), do: s
  defp agent_subagents(%{"subagents" => s}) when is_list(s), do: s
  defp agent_subagents(_), do: []
end
