defmodule Shazam.ConfigSync.CodexGenerator do
  @moduledoc "Generates AGENTS.md — a single markdown file describing all agents for Codex."

  def generate(workspace, agents, _skills, mission, _tech_stack, _memories \\ %{}, preview \\ false, subagents \\ []) do
    content = build_agents_md(agents, mission, subagents)
    file = %{path: Path.join(workspace, "AGENTS.md"), content: content, type: "context"}

    unless preview do
      File.mkdir_p!(Path.dirname(file.path))
      # Only write if file doesn't exist or was generated by Shazam
      should_write = !File.exists?(file.path) ||
        (File.read!(file.path) |> String.contains?("Generated by Shazam"))
      if should_write do
        File.write!(file.path, file.content)
      end
    end

    [file]
  end

  defp build_agents_md(agents, mission, all_subagents) do
    header = Shazam.ConfigSync.header()

    mission_line =
      if mission && mission != "" do
        "\n> #{mission}\n"
      else
        ""
      end

    # Team structure overview
    pms = Enum.filter(agents, fn a -> is_pm?(a) end)
    devs = Enum.filter(agents, fn a -> !is_pm?(a) end)

    overview =
      cond do
        length(pms) > 0 && length(devs) > 0 ->
          pm_names = Enum.map_join(pms, ", ", &agent_name/1)
          "\n**Team**: #{length(pms)} PM (#{pm_names}) + #{length(devs)} developers\n"

        length(devs) > 0 ->
          "\n**Team**: #{length(devs)} developers\n"

        true ->
          ""
      end

    # Agent sections with their subagents listed inline
    agent_sections =
      Enum.map_join(agents, "\n\n", fn agent ->
        build_agent_section(agent, agents, all_subagents)
      end)

    """
    #{header}# #{mission} — Agent Team
    #{mission_line}#{overview}
    ## Team & Subagents

    #{agent_sections}
    """
  end

  defp build_agent_section(agent, all_agents, all_subagents) do
    name = agent_name(agent)
    role = agent_role(agent)
    sup = agent_supervisor(agent)

    # Header
    header_line = "### #{name} — #{role}"

    # Reports to / Top-level
    supervisor_line =
      if sup do
        "- **Reports to**: #{sup}"
      else
        "- **Reports to**: Top-level agent (no supervisor)"
      end

    # Manages
    subordinates = Enum.filter(all_agents, fn a -> agent_supervisor(a) == name end)

    manages_line =
      if length(subordinates) > 0 do
        sub_names = Enum.map_join(subordinates, ", ", &agent_name/1)
        "- **Manages**: #{sub_names}"
      else
        nil
      end

    # Subagents
    agent_subs = agent_subagents(agent)

    subagents_line =
      if is_list(agent_subs) && length(agent_subs) > 0 do
        sub_refs = Enum.map_join(agent_subs, ", ", fn s -> "@#{name}--#{s}" end)
        "- **Subagents**: #{sub_refs}"
      else
        nil
      end

    # Build metadata lines
    meta_lines =
      [supervisor_line, manages_line, subagents_line]
      |> Enum.reject(&is_nil/1)
      |> Enum.join("\n")

    # Subagent detail sections
    subagent_details =
      if is_list(agent_subs) && length(agent_subs) > 0 do
        Enum.map_join(agent_subs, "\n\n", fn sub_name ->
          preset = Enum.find(all_subagents, fn sa -> sa.name == sub_name end)

          if preset do
            model = Shazam.ModelProxy.resolve("codex", preset.default_model)

            """
            #### #{name}--#{sub_name}
            - **Description**: #{preset.description}
            - **Model**: #{model}
            - **Readonly**: #{preset.readonly}

            #{String.trim(preset.prompt)}
            """
            |> String.trim_trailing()
          else
            "#### #{name}--#{sub_name}\n(preset not found)"
          end
        end)
      else
        ""
      end

    base =
      """
      #{header_line}
      #{meta_lines}
      """
      |> String.trim_trailing()

    if subagent_details != "" do
      "#{base}\n\n#{subagent_details}"
    else
      base
    end
  end

  # --- Helpers ---

  defp is_pm?(agent) do
    role = agent_role(agent)
    String.contains?(String.downcase(role), "manager")
  end

  defp agent_name(%{name: n}), do: n
  defp agent_name(%{"name" => n}), do: n
  defp agent_name(_), do: "unnamed"

  defp agent_role(%{role: r}), do: r
  defp agent_role(%{"role" => r}), do: r
  defp agent_role(_), do: ""

  defp agent_supervisor(%{supervisor: s}), do: s
  defp agent_supervisor(%{"supervisor" => s}), do: s
  defp agent_supervisor(_), do: nil

  defp agent_subagents(%{subagents: s}) when is_list(s), do: s
  defp agent_subagents(%{"subagents" => s}) when is_list(s), do: s
  defp agent_subagents(_), do: []
end
