defmodule Shazam.ConfigSync.CursorGenerator do
  @moduledoc "Generates .cursor/agents/*.md and .agents/skills/*/SKILL.md"

  # No longer generating per-agent files — Shazam agents are daemon-managed.
  # Only namespaced subagent files ({agent}--{subagent}.md) are generated.

  def generate(workspace, agents, skills, mission, _tech_stack, _memories \\ %{}, preview \\ false, subagents \\ []) do
    files = []

    # DO NOT generate agent files for Shazam agents (pm, senior_1, etc.)
    # They are daemon-managed, not Cursor subagents.

    # Generate namespaced subagent files: {agent}--{subagent}.md
    subagent_files =
      agents
      |> Enum.flat_map(fn agent ->
        name = agent_name(agent)
        agent_subs = agent_subagents(agent)

        Enum.map(agent_subs, fn sub_name ->
          preset = Enum.find(subagents, fn sa -> sa.name == sub_name end)

          if preset do
            filename = "#{name}--#{sub_name}.md"
            content = build_namespaced_subagent_md(agent, preset, mission)
            %{path: Path.join(workspace, ".cursor/agents/#{filename}"), content: content, type: "subagent"}
          end
        end)
        |> Enum.reject(&is_nil/1)
      end)

    files = files ++ subagent_files

    # Generate skill files in .agents/skills/
    skill_files =
      Enum.map(skills, fn skill ->
        content = build_skill_md(skill)
        sname = skill["name"] || "unnamed"
        %{path: Path.join(workspace, ".agents/skills/#{sname}/SKILL.md"), content: content, type: "skill"}
      end)

    files = files ++ skill_files

    unless preview do
      Enum.each(files, fn file ->
        File.mkdir_p!(Path.dirname(file.path))
        should_write = !File.exists?(file.path) ||
          (File.read!(file.path) |> String.contains?("Generated by Shazam"))
        if should_write, do: File.write!(file.path, file.content)
      end)

      cleanup_orphaned_files(workspace, agents)
    end

    files
  end

  defp cleanup_orphaned_files(workspace, agents) do
    dir = Path.join(workspace, ".cursor/agents")
    if File.dir?(dir) do
      expected =
        agents
        |> Enum.flat_map(fn agent ->
          name = agent_name(agent)
          subs = agent_subagents(agent)
          Enum.map(subs, fn sub -> "#{name}--#{sub}.md" end)
        end)
        |> MapSet.new()

      dir
      |> File.ls!()
      |> Enum.filter(&String.ends_with?(&1, ".md"))
      |> Enum.each(fn file ->
        unless MapSet.member?(expected, file) do
          path = Path.join(dir, file)
          if File.read!(path) |> String.contains?("Generated by Shazam"), do: File.rm!(path)
        end
      end)
    end
  end

  defp build_namespaced_subagent_md(parent_agent, preset, mission) do
    header = Shazam.ConfigSync.header()
    parent_name = agent_name(parent_agent)
    parent_role = agent_role(parent_agent)
    sub_name = preset.name
    sub_desc = preset.description || ""
    sub_model = Shazam.ModelProxy.resolve("cursor", preset.default_model || "sonnet")
    sub_prompt = preset.prompt || ""
    is_readonly = preset.readonly || false

    """
    #{header}---
    name: #{parent_name}--#{sub_name}
    description: #{sub_desc} — subagent of #{parent_name} (#{parent_role})
    model: #{sub_model}
    readonly: #{is_readonly}
    is_background: false
    ---

    You are **#{sub_name}**, a specialized subagent of **#{parent_name}** (#{parent_role}) in the **#{mission}** project.

    #{String.trim(sub_prompt)}
    """
  end

  defp build_skill_md(skill) do
    header = Shazam.ConfigSync.header()
    name = skill["name"] || "unnamed"
    description = skill["description"] || ""
    prompt = skill["prompt"] || ""

    """
    #{header}---
    name: #{name}
    description: #{description}
    ---

    #{prompt}
    """
  end

  # --- Helpers ---

  defp agent_name(%{name: n}), do: n
  defp agent_name(%{"name" => n}), do: n
  defp agent_name(_), do: "unnamed"

  defp agent_role(%{role: r}), do: r
  defp agent_role(%{"role" => r}), do: r
  defp agent_role(_), do: ""

  defp agent_subagents(%{subagents: s}) when is_list(s), do: s
  defp agent_subagents(%{"subagents" => s}) when is_list(s), do: s
  defp agent_subagents(_), do: []
end
