defmodule Shazam.ConfigSync.GeminiGenerator do
  @moduledoc "Generates .gemini/agents/*.md and GEMINI.md"

  @tool_map %{
    "Read" => "read_file",
    "Edit" => "edit_file",
    "Write" => "write_new_file",
    "Bash" => "shell",
    "Grep" => "grep_search",
    "Glob" => "list_directory",
    "WebSearch" => "google_search"
  }

  # No longer generating per-agent files — Shazam agents are daemon-managed.
  # Only namespaced subagent files ({agent}--{subagent}.md) are generated.

  def generate(workspace, agents, skills, mission, tech_stack, memories \\ %{}, preview \\ false, subagents \\ []) do
    files = []

    # Generate GEMINI.md (with team info + subagent references)
    gemini_md = build_gemini_md(agents, mission, tech_stack, memories, subagents)
    files = files ++ [%{path: Path.join(workspace, "GEMINI.md"), content: gemini_md, type: "context"}]

    # DO NOT generate agent files for Shazam agents (pm, senior_1, etc.)
    # They are daemon-managed, not Gemini subagents.

    # Generate namespaced subagent files: {agent}--{subagent}.md
    subagent_files =
      agents
      |> Enum.flat_map(fn agent ->
        name = agent_name(agent)
        agent_subs = agent_subagents(agent)

        Enum.map(agent_subs, fn sub_name ->
          preset = Enum.find(subagents, fn sa -> sa.name == sub_name end)

          if preset do
            filename = "#{name}--#{sub_name}.md"
            content = build_namespaced_subagent_md(agent, preset, mission)
            %{path: Path.join(workspace, ".gemini/agents/#{filename}"), content: content, type: "subagent"}
          end
        end)
        |> Enum.reject(&is_nil/1)
      end)

    files = files ++ subagent_files

    # Generate skill files
    skill_files =
      Enum.map(skills, fn skill ->
        content = build_skill_md(skill)
        sname = skill["name"] || "unnamed"
        %{path: Path.join(workspace, ".gemini/skills/#{sname}/SKILL.md"), content: content, type: "skill"}
      end)

    files = files ++ skill_files

    unless preview do
      Enum.each(files, fn file ->
        File.mkdir_p!(Path.dirname(file.path))
        should_write = !File.exists?(file.path) ||
          (File.read!(file.path) |> String.contains?("Generated by Shazam"))
        if should_write, do: File.write!(file.path, file.content)
      end)

      cleanup_orphaned_files(workspace, agents)
    end

    files
  end

  defp cleanup_orphaned_files(workspace, agents) do
    dir = Path.join(workspace, ".gemini/agents")
    if File.dir?(dir) do
      expected =
        agents
        |> Enum.flat_map(fn agent ->
          name = agent_name(agent)
          subs = agent_subagents(agent)
          Enum.map(subs, fn sub -> "#{name}--#{sub}.md" end)
        end)
        |> MapSet.new()

      dir
      |> File.ls!()
      |> Enum.filter(&String.ends_with?(&1, ".md"))
      |> Enum.each(fn file ->
        unless MapSet.member?(expected, file) do
          path = Path.join(dir, file)
          if File.read!(path) |> String.contains?("Generated by Shazam"), do: File.rm!(path)
        end
      end)
    end
  end

  defp build_gemini_md(agents, mission, tech_stack, memories, _all_subagents) do
    header = Shazam.ConfigSync.header()

    mission_section =
      if mission && mission != "" do
        "# #{mission}\n\n## Project Overview\nThis project uses a managed agent team coordinated by Shazam.\n"
      else
        "# Project\n"
      end

    tech_section =
      if tech_stack && tech_stack != %{} do
        items = Enum.map_join(tech_stack, "\n", fn {k, v} -> "- **#{k}**: #{v}" end)
        "\n## Tech Stack\n#{items}\n"
      else
        ""
      end

    # Team & Subagents section
    team_subagents_section =
      if length(agents) > 0 do
        pms = Enum.count(agents, fn a -> is_pm?(a) end)
        devs = Enum.count(agents, fn a -> !is_pm?(a) end)

        team_summary =
          cond do
            pms > 0 && devs > 0 ->
              "This project uses a managed agent team with #{pms} PM and #{devs} developers."

            devs > 0 ->
              "This project uses a team of #{devs} developers."

            true ->
              "This project uses a managed agent team."
          end

        agent_entries =
          Enum.map_join(agents, "\n\n", fn a ->
            name = agent_name(a)
            role = agent_role(a)
            sup = agent_supervisor(a)
            supervisor = if sup, do: " (reports to #{sup})", else: " (top-level)"
            subs = agent_subagents(a)

            subagent_line =
              if is_list(subs) && length(subs) > 0 do
                sub_refs = Enum.map_join(subs, ", ", fn s -> "@#{name}--#{s}" end)
                "\nSubagents: #{sub_refs}"
              else
                ""
              end

            "### #{name} (#{role})#{supervisor}#{subagent_line}"
          end)

        "\n## Team & Subagents\n#{team_summary}\n\n#{agent_entries}\n"
      else
        ""
      end

    domains_section = build_domains_section(agents)

    # Project memories
    memories_section = build_memories_section(memories[:project], "Project Knowledge")
    rules_section = build_memories_section(memories[:rules], "Rules")
    decisions_section = build_memories_section(memories[:decisions], "Decisions")

    """
    #{header}#{mission_section}#{tech_section}#{team_subagents_section}#{domains_section}#{memories_section}#{rules_section}#{decisions_section}
    ## Guidelines
    - Follow existing code patterns and conventions
    - Write tests for new features
    - Keep changes focused and minimal
    - Report issues to the PM agent
    """
  end

  defp build_memories_section(nil, _title), do: ""
  defp build_memories_section([], _title), do: ""

  defp build_memories_section(memories, title) do
    content =
      Enum.map_join(memories, "\n\n", fn m ->
        "### #{String.capitalize(m.name)}\n#{m.content}"
      end)

    "\n## #{title}\n#{content}\n"
  end

  defp build_domains_section(agents) do
    domains =
      agents
      |> Enum.flat_map(fn a ->
        domain = agent_domain(a)
        if domain && domain != "", do: [domain], else: []
      end)
      |> Enum.uniq()

    if length(domains) > 0 do
      items = Enum.map_join(domains, "\n", fn d -> "- **#{d}**" end)
      "\n## Domains\n#{items}\n"
    else
      ""
    end
  end

  defp build_namespaced_subagent_md(parent_agent, preset, mission) do
    header = Shazam.ConfigSync.header()
    parent_name = agent_name(parent_agent)
    parent_role = agent_role(parent_agent)
    sub_name = preset.name
    sub_desc = preset.description || ""
    sub_model = Shazam.ModelProxy.resolve("gemini", preset.default_model || "sonnet")
    sub_prompt = preset.prompt || ""
    is_readonly = preset.readonly || false

    # Map tools to Gemini names
    gemini_tools =
      if is_list(preset.tools) do
        Enum.map(preset.tools, fn t -> Map.get(@tool_map, t, String.downcase(t)) end)
      else
        []
      end

    tools_yaml =
      if length(gemini_tools) > 0 do
        items = Enum.map_join(gemini_tools, "\n", fn t -> "  - #{t}" end)
        "tools:\n#{items}\n"
      else
        ""
      end

    temperature = if is_readonly, do: "0.5", else: "0.7"

    """
    #{header}---
    name: #{parent_name}--#{sub_name}
    description: #{sub_desc} — subagent of #{parent_name} (#{parent_role})
    kind: local
    model: #{sub_model}
    temperature: #{temperature}
    max_turns: 25
    #{tools_yaml}---

    You are **#{sub_name}**, a specialized subagent of **#{parent_name}** (#{parent_role}) in the **#{mission}** project.

    #{String.trim(sub_prompt)}
    """
  end

  defp build_skill_md(skill) do
    header = Shazam.ConfigSync.header()
    name = skill["name"] || "unnamed"
    description = skill["description"] || ""
    prompt = skill["prompt"] || ""

    """
    #{header}---
    name: #{name}
    description: #{description}
    ---

    #{prompt}
    """
  end

  # --- Helpers ---

  defp is_pm?(agent) do
    role = agent_role(agent)
    String.contains?(String.downcase(role), "manager")
  end

  defp agent_name(%{name: n}), do: n
  defp agent_name(%{"name" => n}), do: n
  defp agent_name(_), do: "unnamed"

  defp agent_role(%{role: r}), do: r
  defp agent_role(%{"role" => r}), do: r
  defp agent_role(_), do: ""

  defp agent_supervisor(%{supervisor: s}), do: s
  defp agent_supervisor(%{"supervisor" => s}), do: s
  defp agent_supervisor(_), do: nil

  defp agent_domain(%{domain: d}), do: d
  defp agent_domain(%{"domain" => d}), do: d
  defp agent_domain(_), do: nil

  defp agent_subagents(%{subagents: s}) when is_list(s), do: s
  defp agent_subagents(%{"subagents" => s}) when is_list(s), do: s
  defp agent_subagents(_), do: []
end
