defmodule Shazam.ConfigSyncTest do
  use ExUnit.Case, async: true

  alias Shazam.ConfigSync.{ClaudeGenerator, GeminiGenerator, CursorGenerator, CodexGenerator}

  setup do
    tmp = Path.join(System.tmp_dir!(), "shazam_sync_test_#{System.unique_integer([:positive])}")
    File.mkdir_p!(tmp)
    on_exit(fn -> File.rm_rf!(tmp) end)

    agents = [
      %{
        name: "pm",
        role: "Project Manager",
        supervisor: nil,
        model: "claude-haiku-4-5-20251001",
        tools: ["Read", "Grep", "Glob", "Bash"],
        skills: [],
        modules: [],
        domain: nil,
        system_prompt: "You manage the team.",
        budget: 200_000,
        heartbeat_interval: 60_000
      },
      %{
        name: "dev1",
        role: "Senior Developer",
        supervisor: "pm",
        model: nil,
        tools: ["Read", "Edit", "Write", "Bash", "Grep", "Glob"],
        skills: [],
        modules: ["auth"],
        domain: "backend",
        system_prompt: nil,
        budget: 100_000,
        heartbeat_interval: 60_000
      }
    ]

    skills = [
      %{
        "name" => "plan",
        "description" => "Create execution plan",
        "prompt" => "Analyze and create a plan..."
      },
      %{
        "name" => "review",
        "description" => "Review PR changes",
        "prompt" => "Review the PR..."
      }
    ]

    {:ok, workspace: tmp, agents: agents, skills: skills}
  end

  # ── ClaudeGenerator ──────────────────────────────────────

  describe "ClaudeGenerator" do
    test "generates CLAUDE.md", %{workspace: ws, agents: agents} do
      files = ClaudeGenerator.generate(ws, agents, [], "Test Project", %{}, %{}, false)
      claude_md = Enum.find(files, &(&1.type == "context"))
      assert claude_md
      assert File.exists?(claude_md.path)
      content = File.read!(claude_md.path)
      assert String.contains?(content, "Test Project")
      assert String.contains?(content, "Generated by Shazam")
      assert String.contains?(content, "pm")
      assert String.contains?(content, "dev1")
    end

    test "generates agent files", %{workspace: ws, agents: agents} do
      files = ClaudeGenerator.generate(ws, agents, [], "Test", %{}, %{}, false)
      agent_files = Enum.filter(files, &(&1.type == "agent"))
      assert length(agent_files) == 2

      pm_file = Enum.find(agent_files, &String.contains?(&1.path, "pm.md"))
      assert pm_file
      content = File.read!(pm_file.path)
      assert String.contains?(content, "name: pm")
      assert String.contains?(content, "model: haiku")
      assert String.contains?(content, "Project Manager")
    end

    test "generates skill files", %{workspace: ws, agents: agents, skills: skills} do
      files = ClaudeGenerator.generate(ws, agents, skills, "Test", %{}, %{}, false)
      skill_files = Enum.filter(files, &(&1.type == "skill"))
      assert length(skill_files) == 2

      plan_file = Enum.find(skill_files, &String.contains?(&1.path, "plan"))
      assert plan_file
      content = File.read!(plan_file.path)
      assert String.contains?(content, "name: \"plan\"")
    end

    test "preview mode does not write files", %{workspace: ws, agents: agents} do
      files = ClaudeGenerator.generate(ws, agents, [], "Test", %{}, %{}, true)
      assert length(files) > 0
      Enum.each(files, fn f -> refute File.exists?(f.path) end)
    end

    test "includes tech stack in CLAUDE.md", %{workspace: ws, agents: agents} do
      tech = %{"language" => "Elixir", "framework" => "Phoenix"}
      files = ClaudeGenerator.generate(ws, agents, [], "Test", tech, %{}, false)
      claude_md = Enum.find(files, &(&1.type == "context"))
      content = File.read!(claude_md.path)
      assert String.contains?(content, "Elixir")
      assert String.contains?(content, "Phoenix")
    end

    test "includes subordinates in PM agent", %{workspace: ws, agents: agents} do
      files = ClaudeGenerator.generate(ws, agents, [], "Test", %{}, %{}, false)
      pm_file = Enum.find(files, &String.contains?(&1.path, "pm.md"))
      content = File.read!(pm_file.path)
      assert String.contains?(content, "dev1")
      assert String.contains?(content, "Your Team")
    end

    test "includes modules in dev agent", %{workspace: ws, agents: agents} do
      files = ClaudeGenerator.generate(ws, agents, [], "Test", %{}, %{}, false)
      dev_file = Enum.find(files, &String.contains?(&1.path, "dev1.md"))
      content = File.read!(dev_file.path)
      assert String.contains?(content, "auth")
    end

    test "includes system prompt in agent file", %{workspace: ws, agents: agents} do
      files = ClaudeGenerator.generate(ws, agents, [], "Test", %{}, %{}, false)
      pm_file = Enum.find(files, &String.contains?(&1.path, "pm.md"))
      content = File.read!(pm_file.path)
      assert String.contains?(content, "You manage the team.")
      assert String.contains?(content, "## Instructions")
    end

    test "includes rich description in agent", %{workspace: ws, agents: agents} do
      files = ClaudeGenerator.generate(ws, agents, [], "Test", %{}, %{}, false)
      pm_file = Enum.find(files, &String.contains?(&1.path, "pm.md"))
      content = File.read!(pm_file.path)
      assert String.contains?(content, "description: Project Manager")
      assert String.contains?(content, "breaks tasks into subtasks")
    end

    test "includes responsibilities for PM", %{workspace: ws, agents: agents} do
      files = ClaudeGenerator.generate(ws, agents, [], "Test", %{}, %{}, false)
      pm_file = Enum.find(files, &String.contains?(&1.path, "pm.md"))
      content = File.read!(pm_file.path)
      assert String.contains?(content, "## Responsibilities")
      assert String.contains?(content, "NEVER implement code yourself")
      assert String.contains?(content, "## Output Format")
    end

    test "includes budget when present", %{workspace: ws, agents: agents} do
      files = ClaudeGenerator.generate(ws, agents, [], "Test", %{}, %{}, false)
      pm_file = Enum.find(files, &String.contains?(&1.path, "pm.md"))
      content = File.read!(pm_file.path)
      assert String.contains?(content, "## Budget")
      assert String.contains?(content, "200,000 tokens")
    end

    test "includes domain for dev agents", %{workspace: ws, agents: agents} do
      files = ClaudeGenerator.generate(ws, agents, [], "Test", %{}, %{}, false)
      dev_file = Enum.find(files, &String.contains?(&1.path, "dev1.md"))
      content = File.read!(dev_file.path)
      assert String.contains?(content, "## Domain")
      assert String.contains?(content, "backend")
    end

    test "dev agent has constraints section", %{workspace: ws, agents: agents} do
      files = ClaudeGenerator.generate(ws, agents, [], "Test", %{}, %{}, false)
      dev_file = Enum.find(files, &String.contains?(&1.path, "dev1.md"))
      content = File.read!(dev_file.path)
      assert String.contains?(content, "## Constraints")
      assert String.contains?(content, "Report to **pm**")
    end

    test "CLAUDE.md includes team summary", %{workspace: ws, agents: agents} do
      files = ClaudeGenerator.generate(ws, agents, [], "Test Project", %{}, %{}, false)
      claude_md = Enum.find(files, &(&1.type == "context"))
      content = File.read!(claude_md.path)
      assert String.contains?(content, "## Team")
      assert String.contains?(content, "1 PM and 1 developers")
      assert String.contains?(content, "## Guidelines")
    end

    test "PM team section has table format", %{workspace: ws, agents: agents} do
      files = ClaudeGenerator.generate(ws, agents, [], "Test", %{}, %{}, false)
      pm_file = Enum.find(files, &String.contains?(&1.path, "pm.md"))
      content = File.read!(pm_file.path)
      assert String.contains?(content, "| Agent | Role | Domain | Tools |")
      assert String.contains?(content, "Manages: dev1")
    end

    test "includes tools in agent frontmatter", %{workspace: ws, agents: agents} do
      files = ClaudeGenerator.generate(ws, agents, [], "Test", %{}, %{}, false)
      pm_file = Enum.find(files, &String.contains?(&1.path, "pm.md"))
      content = File.read!(pm_file.path)
      assert String.contains?(content, "tools: Read, Grep, Glob, Bash")
    end

    test "model defaults to inherit when nil", %{workspace: ws, agents: agents} do
      files = ClaudeGenerator.generate(ws, agents, [], "Test", %{}, %{}, false)
      dev_file = Enum.find(files, &String.contains?(&1.path, "dev1.md"))
      content = File.read!(dev_file.path)
      assert String.contains?(content, "model: inherit")
    end

    test "handles empty agents list", %{workspace: ws} do
      files = ClaudeGenerator.generate(ws, [], [], "Test", %{}, %{}, false)
      claude_md = Enum.find(files, &(&1.type == "context"))
      assert claude_md
      content = File.read!(claude_md.path)
      assert String.contains?(content, "Test")
      refute String.contains?(content, "Agent Team")
    end

    test "generates settings.json", %{workspace: ws, agents: agents} do
      files = ClaudeGenerator.generate(ws, agents, [], "Test", %{}, %{}, false)
      settings_file = Enum.find(files, &(&1.type == "settings"))
      assert settings_file
      assert File.exists?(settings_file.path)
      content = File.read!(settings_file.path)
      assert String.contains?(content, "permissions")
      assert String.contains?(content, "Bash(*)")
      assert String.contains?(content, "Read")
    end

    test "generates rules file", %{workspace: ws, agents: agents} do
      files = ClaudeGenerator.generate(ws, agents, [], "Test Mission", %{}, %{}, false)
      rules_file = Enum.find(files, &(&1.type == "rules"))
      assert rules_file
      assert File.exists?(rules_file.path)
      content = File.read!(rules_file.path)
      assert String.contains?(content, "Generated by Shazam")
      assert String.contains?(content, "Test Mission")
      assert String.contains?(content, "2 agents")
    end

    test "does not overwrite user-created files", %{workspace: ws, agents: agents} do
      # First generate files
      ClaudeGenerator.generate(ws, agents, [], "Test", %{}, %{}, false)
      # Manually overwrite a file without the Shazam header
      claude_md_path = Path.join(ws, "CLAUDE.md")
      File.write!(claude_md_path, "# My custom CLAUDE.md\nDo not overwrite me.")
      # Re-generate — should NOT overwrite
      ClaudeGenerator.generate(ws, agents, [], "Test v2", %{}, %{}, false)
      content = File.read!(claude_md_path)
      assert String.contains?(content, "My custom CLAUDE.md")
      refute String.contains?(content, "Test v2")
    end

    test "does not regenerate settings.json if it already exists", %{workspace: ws, agents: agents} do
      ClaudeGenerator.generate(ws, agents, [], "Test", %{}, %{}, false)
      settings_path = Path.join(ws, ".claude/settings.json")
      assert File.exists?(settings_path)
      # Overwrite with custom content (no Shazam header)
      File.write!(settings_path, "{\"custom\": true}")
      # Re-generate
      files = ClaudeGenerator.generate(ws, agents, [], "Test", %{}, %{}, false)
      # settings.json should not be in the file list since it already exists
      settings_file = Enum.find(files, &(&1.type == "settings"))
      assert settings_file == nil
    end

    test "handles empty skills list", %{workspace: ws, agents: agents} do
      files = ClaudeGenerator.generate(ws, agents, [], "Test", %{}, %{}, false)
      skill_files = Enum.filter(files, &(&1.type == "skill"))
      assert length(skill_files) == 0
    end
  end

  # ── GeminiGenerator ──────────────────────────────────────

  describe "GeminiGenerator" do
    test "generates GEMINI.md", %{workspace: ws, agents: agents} do
      files = GeminiGenerator.generate(ws, agents, [], "Test", %{}, %{}, false)
      gemini_md = Enum.find(files, &(&1.type == "context"))
      assert gemini_md
      assert String.contains?(gemini_md.path, "GEMINI.md")
      content = File.read!(gemini_md.path)
      assert String.contains?(content, "Test")
    end

    test "maps tools to Gemini names", %{workspace: ws, agents: agents} do
      files = GeminiGenerator.generate(ws, agents, [], "Test", %{}, %{}, false)
      pm_file = Enum.find(files, &String.contains?(&1.path, ".gemini/agents/pm.md"))
      assert pm_file
      content = File.read!(pm_file.path)
      assert String.contains?(content, "read_file")
      assert String.contains?(content, "grep_search")
      assert String.contains?(content, "shell")
      assert String.contains?(content, "list_directory")
    end

    test "generates agents in .gemini/agents/", %{workspace: ws, agents: agents} do
      files = GeminiGenerator.generate(ws, agents, [], "Test", %{}, %{}, false)
      agent_files = Enum.filter(files, &(&1.type == "agent"))

      Enum.each(agent_files, fn f ->
        assert String.contains?(f.path, ".gemini/agents/")
      end)
    end

    test "includes kind and temperature in frontmatter", %{workspace: ws, agents: agents} do
      files = GeminiGenerator.generate(ws, agents, [], "Test", %{}, %{}, false)
      pm_file = Enum.find(files, &String.contains?(&1.path, "pm.md"))
      content = File.read!(pm_file.path)
      assert String.contains?(content, "kind: local")
      # PM gets lower temperature (0.5) for structured output
      assert String.contains?(content, "temperature: 0.5")
      # PM gets more turns (30) for coordination
      assert String.contains?(content, "max_turns: 30")
    end

    test "dev agents get higher temperature and fewer turns", %{workspace: ws, agents: agents} do
      files = GeminiGenerator.generate(ws, agents, [], "Test", %{}, %{}, false)
      dev_file = Enum.find(files, &String.contains?(&1.path, "dev1.md"))
      content = File.read!(dev_file.path)
      assert String.contains?(content, "temperature: 0.7")
      assert String.contains?(content, "max_turns: 25")
    end

    test "maps haiku model to gemini-2.0-flash", %{workspace: ws, agents: agents} do
      files = GeminiGenerator.generate(ws, agents, [], "Test", %{}, %{}, false)
      pm_file = Enum.find(files, &String.contains?(&1.path, "pm.md"))
      content = File.read!(pm_file.path)
      assert String.contains?(content, "model: gemini-2.0-flash")
    end

    test "preview mode does not write files", %{workspace: ws, agents: agents} do
      files = GeminiGenerator.generate(ws, agents, [], "Test", %{}, %{}, true)
      assert length(files) > 0
      Enum.each(files, fn f -> refute File.exists?(f.path) end)
    end

    test "generates skill files", %{workspace: ws, agents: agents, skills: skills} do
      files = GeminiGenerator.generate(ws, agents, skills, "Test", %{}, %{}, false)
      skill_files = Enum.filter(files, &(&1.type == "skill"))
      assert length(skill_files) == 2
    end

    test "handles empty agents list", %{workspace: ws} do
      files = GeminiGenerator.generate(ws, [], [], "Test", %{}, %{}, false)
      assert length(files) == 1
      gemini_md = hd(files)
      assert gemini_md.type == "context"
    end

    test "includes tools array in frontmatter", %{workspace: ws, agents: agents} do
      files = GeminiGenerator.generate(ws, agents, [], "Test", %{}, %{}, false)
      dev_file = Enum.find(files, &String.contains?(&1.path, "dev1.md"))
      content = File.read!(dev_file.path)
      assert String.contains?(content, "tools:")
      assert String.contains?(content, "  - edit_file")
      assert String.contains?(content, "  - write_new_file")
    end

    test "includes responsibilities and constraints", %{workspace: ws, agents: agents} do
      files = GeminiGenerator.generate(ws, agents, [], "Test", %{}, %{}, false)
      pm_file = Enum.find(files, &String.contains?(&1.path, "pm.md"))
      content = File.read!(pm_file.path)
      assert String.contains?(content, "## Responsibilities")
      assert String.contains?(content, "NEVER implement code yourself")
    end

    test "GEMINI.md includes team summary", %{workspace: ws, agents: agents} do
      files = GeminiGenerator.generate(ws, agents, [], "Test", %{}, %{}, false)
      gemini_md = Enum.find(files, &(&1.type == "context"))
      content = File.read!(gemini_md.path)
      assert String.contains?(content, "## Team")
      assert String.contains?(content, "## Guidelines")
    end
  end

  # ── CursorGenerator ──────────────────────────────────────

  describe "CursorGenerator" do
    test "generates agents in .cursor/agents/", %{workspace: ws, agents: agents} do
      files = CursorGenerator.generate(ws, agents, [], "Test", %{}, %{}, false)
      agent_files = Enum.filter(files, &(&1.type == "agent"))
      assert length(agent_files) == 2

      Enum.each(agent_files, fn f ->
        assert String.contains?(f.path, ".cursor/agents/")
      end)
    end

    test "uses readonly for non-edit agents", %{workspace: ws, agents: agents} do
      files = CursorGenerator.generate(ws, agents, [], "Test", %{}, %{}, false)
      pm_file = Enum.find(files, &String.contains?(&1.path, "pm.md"))
      content = File.read!(pm_file.path)
      # PM has no Edit/Write tools, should be readonly
      assert String.contains?(content, "readonly: true")
    end

    test "uses readonly false for agents with write tools", %{workspace: ws, agents: agents} do
      files = CursorGenerator.generate(ws, agents, [], "Test", %{}, %{}, false)
      dev_file = Enum.find(files, &String.contains?(&1.path, "dev1.md"))
      content = File.read!(dev_file.path)
      assert String.contains?(content, "readonly: false")
    end

    test "uses fast model for haiku", %{workspace: ws, agents: agents} do
      files = CursorGenerator.generate(ws, agents, [], "Test", %{}, %{}, false)
      pm_file = Enum.find(files, &String.contains?(&1.path, "pm.md"))
      content = File.read!(pm_file.path)
      assert String.contains?(content, "model: fast")
    end

    test "includes is_background field", %{workspace: ws, agents: agents} do
      files = CursorGenerator.generate(ws, agents, [], "Test", %{}, %{}, false)
      pm_file = Enum.find(files, &String.contains?(&1.path, "pm.md"))
      content = File.read!(pm_file.path)
      assert String.contains?(content, "is_background: false")
    end

    test "generates skills in .agents/skills/", %{workspace: ws, agents: agents, skills: skills} do
      files = CursorGenerator.generate(ws, agents, skills, "Test", %{}, %{}, false)
      skill_files = Enum.filter(files, &(&1.type == "skill"))
      assert length(skill_files) == 2

      Enum.each(skill_files, fn f ->
        assert String.contains?(f.path, ".agents/skills/")
      end)
    end

    test "preview mode does not write files", %{workspace: ws, agents: agents} do
      files = CursorGenerator.generate(ws, agents, [], "Test", %{}, %{}, true)
      assert length(files) > 0
      Enum.each(files, fn f -> refute File.exists?(f.path) end)
    end

    test "handles empty agents list", %{workspace: ws} do
      files = CursorGenerator.generate(ws, [], [], "Test", %{}, %{}, false)
      assert length(files) == 0
    end

    test "includes rich description in agent", %{workspace: ws, agents: agents} do
      files = CursorGenerator.generate(ws, agents, [], "Test", %{}, %{}, false)
      pm_file = Enum.find(files, &String.contains?(&1.path, "pm.md"))
      content = File.read!(pm_file.path)
      assert String.contains?(content, "description: Project Manager")
      assert String.contains?(content, "breaks tasks into subtasks")
    end

    test "includes responsibilities and team table", %{workspace: ws, agents: agents} do
      files = CursorGenerator.generate(ws, agents, [], "Test", %{}, %{}, false)
      pm_file = Enum.find(files, &String.contains?(&1.path, "pm.md"))
      content = File.read!(pm_file.path)
      assert String.contains?(content, "## Responsibilities")
      assert String.contains?(content, "| Agent | Role | Domain | Tools |")
    end

    test "dev agent has constraints and domain", %{workspace: ws, agents: agents} do
      files = CursorGenerator.generate(ws, agents, [], "Test", %{}, %{}, false)
      dev_file = Enum.find(files, &String.contains?(&1.path, "dev1.md"))
      content = File.read!(dev_file.path)
      assert String.contains?(content, "## Constraints")
      assert String.contains?(content, "backend")
    end
  end

  # ── CodexGenerator ──────────────────────────────────────

  describe "CodexGenerator" do
    test "generates AGENTS.md", %{workspace: ws, agents: agents} do
      files = CodexGenerator.generate(ws, agents, [], "Test", %{}, %{}, false)
      assert length(files) == 1
      agents_md = hd(files)
      assert String.contains?(agents_md.path, "AGENTS.md")
      content = File.read!(agents_md.path)
      assert String.contains?(content, "pm")
      assert String.contains?(content, "dev1")
      assert String.contains?(content, "Project Manager")
    end

    test "includes Generated by Shazam header", %{workspace: ws, agents: agents} do
      files = CodexGenerator.generate(ws, agents, [], "Test", %{}, %{}, false)
      content = File.read!(hd(files).path)
      assert String.contains?(content, "Generated by Shazam")
    end

    test "includes mission in title", %{workspace: ws, agents: agents} do
      files = CodexGenerator.generate(ws, agents, [], "My Cool Project", %{}, %{}, false)
      content = File.read!(hd(files).path)
      assert String.contains?(content, "My Cool Project")
    end

    test "includes tools for agents", %{workspace: ws, agents: agents} do
      files = CodexGenerator.generate(ws, agents, [], "Test", %{}, %{}, false)
      content = File.read!(hd(files).path)
      assert String.contains?(content, "Read, Edit, Write, Bash, Grep, Glob")
    end

    test "includes supervisor info", %{workspace: ws, agents: agents} do
      files = CodexGenerator.generate(ws, agents, [], "Test", %{}, %{}, false)
      content = File.read!(hd(files).path)
      assert String.contains?(content, "**Reports to**")
      assert String.contains?(content, "Top-level agent")
    end

    test "preview mode does not write files", %{workspace: ws, agents: agents} do
      files = CodexGenerator.generate(ws, agents, [], "Test", %{}, %{}, true)
      assert length(files) == 1
      Enum.each(files, fn f -> refute File.exists?(f.path) end)
    end

    test "handles empty agents list", %{workspace: ws} do
      files = CodexGenerator.generate(ws, [], [], "Test", %{}, %{}, false)
      assert length(files) == 1
      content = File.read!(hd(files).path)
      assert String.contains?(content, "Test")
    end

    test "includes system prompt when present", %{workspace: ws, agents: agents} do
      files = CodexGenerator.generate(ws, agents, [], "Test", %{}, %{}, false)
      content = File.read!(hd(files).path)
      assert String.contains?(content, "You manage the team.")
    end

    test "includes model for agents", %{workspace: ws, agents: agents} do
      files = CodexGenerator.generate(ws, agents, [], "Test", %{}, %{}, false)
      content = File.read!(hd(files).path)
      assert String.contains?(content, "**Model**: claude-haiku-4-5-20251001")
    end

    test "includes budget for agents", %{workspace: ws, agents: agents} do
      files = CodexGenerator.generate(ws, agents, [], "Test", %{}, %{}, false)
      content = File.read!(hd(files).path)
      assert String.contains?(content, "**Budget**: 200,000 tokens")
    end

    test "includes manages line for PM", %{workspace: ws, agents: agents} do
      files = CodexGenerator.generate(ws, agents, [], "Test", %{}, %{}, false)
      content = File.read!(hd(files).path)
      assert String.contains?(content, "**Manages**: dev1")
    end

    test "includes responsibilities section", %{workspace: ws, agents: agents} do
      files = CodexGenerator.generate(ws, agents, [], "Test", %{}, %{}, false)
      content = File.read!(hd(files).path)
      assert String.contains?(content, "**Responsibilities:**")
      assert String.contains?(content, "Never implement code directly")
    end

    test "includes team overview", %{workspace: ws, agents: agents} do
      files = CodexGenerator.generate(ws, agents, [], "Test", %{}, %{}, false)
      content = File.read!(hd(files).path)
      assert String.contains?(content, "## Team Structure")
      assert String.contains?(content, "1 PM")
    end
  end

  # ── ConfigSync.status ──────────────────────────────────────

  describe "ConfigSync.status/1" do
    test "reports no files when workspace is empty", %{workspace: ws} do
      status = Shazam.ConfigSync.status(ws)
      assert status.workspace == ws
      assert status.count == 0
      assert status.synced_files == []
    end

    test "detects generated files", %{workspace: ws, agents: agents} do
      ClaudeGenerator.generate(ws, agents, [], "Test", %{}, %{}, false)
      CodexGenerator.generate(ws, agents, [], "Test", %{}, %{}, false)

      status = Shazam.ConfigSync.status(ws)
      assert status.count > 0

      providers = Enum.map(status.synced_files, & &1.provider)
      assert "claude" in providers
      assert "codex" in providers
    end

    test "detects last sync time from CLAUDE.md", %{workspace: ws, agents: agents} do
      ClaudeGenerator.generate(ws, agents, [], "Test", %{}, %{}, false)
      status = Shazam.ConfigSync.status(ws)
      assert status.last_sync != nil
    end
  end

  # ── Memory Integration ──────────────────────────────────────

  describe "memory integration" do
    setup %{workspace: ws} do
      # Create memory directories and files
      memories_base = Path.join(ws, ".shazam/memories")
      Enum.each(["project", "rules", "decisions", "agents"], fn dir ->
        File.mkdir_p!(Path.join(memories_base, dir))
      end)

      # Project memory
      File.write!(Path.join(memories_base, "project/overview.md"), """
      ---
      name: overview
      description: Project overview
      tags: project
      ---

      This is an Elixir/Phoenix web app for managing condos.
      """)

      # Rules memory
      File.write!(Path.join(memories_base, "rules/testing.md"), """
      ---
      name: testing
      description: Testing rules
      tags: testing
      ---

      Always use ExUnit. Run mix test before committing.
      """)

      # Decisions memory
      File.write!(Path.join(memories_base, "decisions/use-ecto.md"), """
      ---
      name: use-ecto
      description: Use Ecto for data layer
      ---

      We chose Ecto for the data layer because of its composability.
      """)

      # Agent memory
      File.write!(Path.join(memories_base, "agents/pm.md"), """
      ---
      name: pm
      description: PM agent memory
      ---

      PM learned that tasks should always have acceptance criteria.
      """)

      File.write!(Path.join(memories_base, "agents/dev1.md"), """
      ---
      name: dev1
      description: Dev1 agent memory
      ---

      Dev1 prefers to use pattern matching over conditionals.
      """)

      {:ok, memories_base: memories_base}
    end

    test "read_memories reads project memories", %{workspace: ws} do
      memories = Shazam.ConfigSync.read_memories(ws)
      assert length(memories.project) == 1
      assert hd(memories.project).name == "overview"
      assert String.contains?(hd(memories.project).content, "Elixir/Phoenix")
    end

    test "read_memories reads rules", %{workspace: ws} do
      memories = Shazam.ConfigSync.read_memories(ws)
      assert length(memories.rules) == 1
      assert hd(memories.rules).name == "testing"
      assert String.contains?(hd(memories.rules).content, "ExUnit")
    end

    test "read_memories reads decisions", %{workspace: ws} do
      memories = Shazam.ConfigSync.read_memories(ws)
      assert length(memories.decisions) == 1
      assert hd(memories.decisions).name == "use-ecto"
    end

    test "read_memories reads agent memories as map", %{workspace: ws} do
      memories = Shazam.ConfigSync.read_memories(ws)
      assert Map.has_key?(memories.agents, "pm")
      assert Map.has_key?(memories.agents, "dev1")
      assert String.contains?(memories.agents["pm"], "acceptance criteria")
    end

    test "read_memories returns empty when no memories dir", %{workspace: ws} do
      empty_ws = Path.join(ws, "empty_workspace")
      File.mkdir_p!(empty_ws)
      memories = Shazam.ConfigSync.read_memories(empty_ws)
      assert memories.project == []
      assert memories.rules == []
      assert memories.decisions == []
      assert memories.agents == %{}
    end

    test "CLAUDE.md includes project memories", %{workspace: ws, agents: agents} do
      memories = Shazam.ConfigSync.read_memories(ws)
      files = ClaudeGenerator.generate(ws, agents, [], "Test", %{}, memories, false)
      claude_md = Enum.find(files, &(&1.type == "context"))
      content = File.read!(claude_md.path)
      assert String.contains?(content, "## Project Knowledge")
      assert String.contains?(content, "Elixir/Phoenix")
    end

    test "CLAUDE.md includes rules memories", %{workspace: ws, agents: agents} do
      memories = Shazam.ConfigSync.read_memories(ws)
      files = ClaudeGenerator.generate(ws, agents, [], "Test", %{}, memories, false)
      claude_md = Enum.find(files, &(&1.type == "context"))
      content = File.read!(claude_md.path)
      assert String.contains?(content, "## Rules")
      assert String.contains?(content, "ExUnit")
    end

    test "CLAUDE.md includes decisions", %{workspace: ws, agents: agents} do
      memories = Shazam.ConfigSync.read_memories(ws)
      files = ClaudeGenerator.generate(ws, agents, [], "Test", %{}, memories, false)
      claude_md = Enum.find(files, &(&1.type == "context"))
      content = File.read!(claude_md.path)
      assert String.contains?(content, "## Decisions")
      assert String.contains?(content, "Ecto")
    end

    test "agent files include agent-specific memory", %{workspace: ws, agents: agents} do
      memories = Shazam.ConfigSync.read_memories(ws)
      files = ClaudeGenerator.generate(ws, agents, [], "Test", %{}, memories, false)
      pm_file = Enum.find(files, &String.contains?(&1.path, "pm.md"))
      content = File.read!(pm_file.path)
      assert String.contains?(content, "## Agent Memory")
      assert String.contains?(content, "acceptance criteria")
    end

    test "GEMINI.md includes project memories", %{workspace: ws, agents: agents} do
      memories = Shazam.ConfigSync.read_memories(ws)
      files = GeminiGenerator.generate(ws, agents, [], "Test", %{}, memories, false)
      gemini_md = Enum.find(files, &(&1.type == "context"))
      content = File.read!(gemini_md.path)
      assert String.contains?(content, "## Project Knowledge")
      assert String.contains?(content, "Elixir/Phoenix")
    end

    test "Gemini agent files include agent-specific memory", %{workspace: ws, agents: agents} do
      memories = Shazam.ConfigSync.read_memories(ws)
      files = GeminiGenerator.generate(ws, agents, [], "Test", %{}, memories, false)
      dev_file = Enum.find(files, &String.contains?(&1.path, "dev1.md"))
      content = File.read!(dev_file.path)
      assert String.contains?(content, "## Agent Memory")
      assert String.contains?(content, "pattern matching")
    end

    test "Cursor agent files include agent-specific memory", %{workspace: ws, agents: agents} do
      memories = Shazam.ConfigSync.read_memories(ws)
      files = CursorGenerator.generate(ws, agents, [], "Test", %{}, memories, false)
      pm_file = Enum.find(files, &String.contains?(&1.path, "pm.md"))
      content = File.read!(pm_file.path)
      assert String.contains?(content, "## Agent Memory")
      assert String.contains?(content, "acceptance criteria")
    end

    test "truncates large memories", %{workspace: ws} do
      # Write a very large memory file (> 2000 chars)
      large_content = """
      ---
      name: large
      description: Large memory
      ---

      #{String.duplicate("This is a long line of content that should be truncated. ", 100)}
      """
      File.write!(Path.join(ws, ".shazam/memories/project/large.md"), large_content)

      memories = Shazam.ConfigSync.read_memories(ws)
      large_mem = Enum.find(memories.project, &(&1.name == "large"))
      assert large_mem
      assert byte_size(large_mem.content) <= 2010  # allow for "..." suffix
      assert String.contains?(large_mem.content, "...")
    end

    test "strips frontmatter from memory content", %{workspace: ws} do
      memories = Shazam.ConfigSync.read_memories(ws)
      overview = hd(memories.project)
      refute String.contains?(overview.content, "---")
      refute String.contains?(overview.content, "tags: project")
    end

    test "skips SKILL.md files in memory dirs", %{workspace: ws} do
      File.write!(Path.join(ws, ".shazam/memories/project/SKILL.md"), "# Index file")
      memories = Shazam.ConfigSync.read_memories(ws)
      names = Enum.map(memories.project, & &1.name)
      refute "SKILL" in names
    end
  end
end
