defmodule Shazam.ConfigImportTest do
  use ExUnit.Case, async: true

  alias Shazam.ConfigImport

  setup do
    tmp = Path.join(System.tmp_dir!(), "shazam_import_test_#{System.unique_integer([:positive])}")
    File.mkdir_p!(tmp)
    on_exit(fn -> File.rm_rf!(tmp) end)
    {:ok, workspace: tmp}
  end

  # ── Claude Import ──────────────────────────────────────

  describe "import Claude agents" do
    test "imports agents from .claude/agents/*.md", %{workspace: ws} do
      agents_dir = Path.join(ws, ".claude/agents")
      File.mkdir_p!(agents_dir)

      File.write!(Path.join(agents_dir, "pm.md"), """
      ---
      name: pm
      description: Project Manager
      model: haiku
      tools: Read, Grep, Glob, Bash
      ---

      You are **pm**, the Project Manager.

      ## Responsibilities
      - Break complex tasks into focused subtasks
      """)

      {:ok, yaml} = ConfigImport.import_from_workspace(ws)
      assert String.contains?(yaml, "pm:")
      assert String.contains?(yaml, "role: Project Manager")
    end

    test "skips Shazam-generated files", %{workspace: ws} do
      agents_dir = Path.join(ws, ".claude/agents")
      File.mkdir_p!(agents_dir)

      File.write!(Path.join(agents_dir, "pm.md"), """
      <!-- Generated by Shazam. Do not edit manually. Run 'shazam sync' to regenerate. -->

      ---
      name: pm
      description: Project Manager
      model: haiku
      ---

      You are pm.
      """)

      assert {:error, :no_configs_found} = ConfigImport.import_from_workspace(ws)
    end

    test "maps Claude model names back to Shazam format", %{workspace: ws} do
      agents_dir = Path.join(ws, ".claude/agents")
      File.mkdir_p!(agents_dir)

      File.write!(Path.join(agents_dir, "dev.md"), """
      ---
      name: dev
      description: Senior Developer
      model: opus
      ---

      You are a developer.
      """)

      {:ok, yaml} = ConfigImport.import_from_workspace(ws)
      assert String.contains?(yaml, "model: claude-opus-4-6")
    end

    test "extracts mission from CLAUDE.md", %{workspace: ws} do
      agents_dir = Path.join(ws, ".claude/agents")
      File.mkdir_p!(agents_dir)

      File.write!(Path.join(agents_dir, "dev.md"), """
      ---
      name: dev
      description: Developer
      model: inherit
      ---

      Dev agent.
      """)

      File.write!(Path.join(ws, "CLAUDE.md"), """
      # Project: My Awesome App
      Some content here.
      """)

      {:ok, yaml} = ConfigImport.import_from_workspace(ws)
      assert String.contains?(yaml, "mission: My Awesome App")
    end
  end

  # ── Skills Import ──────────────────────────────────────

  describe "import skills" do
    test "imports skills from .claude/skills/", %{workspace: ws} do
      agents_dir = Path.join(ws, ".claude/agents")
      File.mkdir_p!(agents_dir)

      File.write!(Path.join(agents_dir, "dev.md"), """
      ---
      name: dev
      description: Developer
      ---

      Dev agent.
      """)

      skill_dir = Path.join(ws, ".claude/skills/plan")
      File.mkdir_p!(skill_dir)

      File.write!(Path.join(skill_dir, "SKILL.md"), """
      ---
      name: plan
      description: Create execution plan
      ---

      Analyze the task and create a plan.
      """)

      {:ok, yaml} = ConfigImport.import_from_workspace(ws)
      assert String.contains?(yaml, "name: plan")
      assert String.contains?(yaml, "description: Create execution plan")
    end

    test "imports commands from .claude/commands/", %{workspace: ws} do
      agents_dir = Path.join(ws, ".claude/agents")
      File.mkdir_p!(agents_dir)

      File.write!(Path.join(agents_dir, "dev.md"), """
      ---
      name: dev
      description: Developer
      ---

      Dev agent.
      """)

      commands_dir = Path.join(ws, ".claude/commands")
      File.mkdir_p!(commands_dir)

      File.write!(Path.join(commands_dir, "deploy.md"), """
      ---
      name: deploy
      description: Deploy to production
      ---

      Run the deployment pipeline.
      """)

      {:ok, yaml} = ConfigImport.import_from_workspace(ws)
      assert String.contains?(yaml, "name: deploy")
    end
  end

  # ── Gemini Import ──────────────────────────────────────

  describe "import Gemini agents" do
    test "imports agents from .gemini/agents/ with tool mapping", %{workspace: ws} do
      agents_dir = Path.join(ws, ".gemini/agents")
      File.mkdir_p!(agents_dir)

      File.write!(Path.join(agents_dir, "dev.md"), """
      ---
      name: dev
      description: Senior Developer
      model: gemini-2.0-flash
      tools: [read_file, edit_file, shell, grep_search]
      ---

      You are a developer.
      """)

      {:ok, yaml} = ConfigImport.import_from_workspace(ws)
      assert String.contains?(yaml, "dev:")
      assert String.contains?(yaml, "role: Senior Developer")
      # Gemini tools should be mapped back to Shazam names
      assert String.contains?(yaml, "- Read")
      assert String.contains?(yaml, "- Edit")
      assert String.contains?(yaml, "- Bash")
      assert String.contains?(yaml, "- Grep")
    end

    test "maps gemini-2.0-flash to haiku model", %{workspace: ws} do
      agents_dir = Path.join(ws, ".gemini/agents")
      File.mkdir_p!(agents_dir)

      File.write!(Path.join(agents_dir, "dev.md"), """
      ---
      name: dev
      description: Developer
      model: gemini-2.0-flash
      ---

      Dev agent.
      """)

      {:ok, yaml} = ConfigImport.import_from_workspace(ws)
      assert String.contains?(yaml, "model: claude-haiku-4-5-20251001")
    end
  end

  # ── Cursor Import ──────────────────────────────────────

  describe "import Cursor agents" do
    test "imports agents from .cursor/agents/", %{workspace: ws} do
      agents_dir = Path.join(ws, ".cursor/agents")
      File.mkdir_p!(agents_dir)

      File.write!(Path.join(agents_dir, "qa.md"), """
      ---
      name: qa
      description: QA Engineer
      model: fast
      ---

      You are a QA engineer.
      """)

      {:ok, yaml} = ConfigImport.import_from_workspace(ws)
      assert String.contains?(yaml, "qa:")
      assert String.contains?(yaml, "role: QA Engineer")
      assert String.contains?(yaml, "model: claude-haiku-4-5-20251001")
    end
  end

  # ── Codex Import ──────────────────────────────────────

  describe "import Codex agents" do
    test "imports agents from AGENTS.md", %{workspace: ws} do
      File.write!(Path.join(ws, "AGENTS.md"), """
      # Team

      ### pm
      **Project Manager**

      ### dev1
      **Senior Developer**
      """)

      {:ok, yaml} = ConfigImport.import_from_workspace(ws)
      assert String.contains?(yaml, "pm:")
      assert String.contains?(yaml, "dev1:")
    end
  end

  # ── Merge ──────────────────────────────────────

  describe "merge agents from multiple providers" do
    test "deduplicates by name, Claude takes priority", %{workspace: ws} do
      # Create same agent in both Claude and Gemini
      claude_dir = Path.join(ws, ".claude/agents")
      gemini_dir = Path.join(ws, ".gemini/agents")
      File.mkdir_p!(claude_dir)
      File.mkdir_p!(gemini_dir)

      File.write!(Path.join(claude_dir, "dev.md"), """
      ---
      name: dev
      description: Claude Developer
      model: opus
      ---

      Claude dev agent.
      """)

      File.write!(Path.join(gemini_dir, "dev.md"), """
      ---
      name: dev
      description: Gemini Developer
      model: gemini-2.5-pro
      ---

      Gemini dev agent.
      """)

      {:ok, yaml} = ConfigImport.import_from_workspace(ws)
      # Claude should win
      assert String.contains?(yaml, "role: Claude Developer")
      refute String.contains?(yaml, "role: Gemini Developer")
    end

    test "supervisorless agents sort before subordinates", %{workspace: ws} do
      agents_dir = Path.join(ws, ".claude/agents")
      File.mkdir_p!(agents_dir)

      File.write!(Path.join(agents_dir, "dev.md"), """
      ---
      name: dev
      description: Developer
      ---

      Reports to **pm**
      """)

      File.write!(Path.join(agents_dir, "pm.md"), """
      ---
      name: pm
      description: Project Manager
      ---

      You are the PM.
      """)

      {:ok, yaml} = ConfigImport.import_from_workspace(ws)
      pm_pos = :binary.match(yaml, "pm:") |> elem(0)
      dev_pos = :binary.match(yaml, "dev:") |> elem(0)
      assert pm_pos < dev_pos
    end
  end

  # ── Missing directories ──────────────────────────────────────

  describe "handle missing directories" do
    test "returns error when no configs exist", %{workspace: ws} do
      assert {:error, :no_configs_found} = ConfigImport.import_from_workspace(ws)
    end

    test "handles empty .claude/agents/ directory", %{workspace: ws} do
      File.mkdir_p!(Path.join(ws, ".claude/agents"))
      assert {:error, :no_configs_found} = ConfigImport.import_from_workspace(ws)
    end
  end

  # ── import_and_save ──────────────────────────────────────

  describe "import_and_save/1" do
    test "writes shazam.yaml to .shazam/ directory", %{workspace: ws} do
      agents_dir = Path.join(ws, ".claude/agents")
      File.mkdir_p!(agents_dir)

      File.write!(Path.join(agents_dir, "dev.md"), """
      ---
      name: dev
      description: Developer
      ---

      Dev agent.
      """)

      {:ok, path, yaml} = ConfigImport.import_and_save(ws)
      assert path == Path.join(ws, ".shazam/shazam.yaml")
      assert File.exists?(path)
      saved = File.read!(path)
      assert saved == yaml
    end

    test "returns error when no configs found", %{workspace: ws} do
      assert {:error, :no_configs_found} = ConfigImport.import_and_save(ws)
    end
  end

  # ── YAML output validity ──────────────────────────────────────

  describe "generated YAML" do
    test "contains expected structure", %{workspace: ws} do
      agents_dir = Path.join(ws, ".claude/agents")
      File.mkdir_p!(agents_dir)

      File.write!(Path.join(agents_dir, "pm.md"), """
      ---
      name: pm
      description: Project Manager
      tools: Read, Grep
      ---

      You are the PM.
      """)

      File.write!(Path.join(agents_dir, "dev.md"), """
      ---
      name: dev
      description: Senior Developer
      tools: Read, Edit, Write
      ---

      Reports to **pm**
      """)

      {:ok, yaml} = ConfigImport.import_from_workspace(ws)
      assert String.contains?(yaml, "# Generated by shazam import")
      assert String.contains?(yaml, "company:")
      assert String.contains?(yaml, "agents:")
      assert String.contains?(yaml, "config:")
      assert String.contains?(yaml, "auto_approve: false")
      assert String.contains?(yaml, "max_concurrent: 4")
    end

    test "includes supervisor in YAML", %{workspace: ws} do
      agents_dir = Path.join(ws, ".claude/agents")
      File.mkdir_p!(agents_dir)

      File.write!(Path.join(agents_dir, "dev.md"), """
      ---
      name: dev
      description: Developer
      ---

      Reports to **pm**
      """)

      {:ok, yaml} = ConfigImport.import_from_workspace(ws)
      assert String.contains?(yaml, "supervisor: pm")
    end
  end
end
