defmodule Shazam.ConfigSyncStatusTest do
  use ExUnit.Case, async: true

  alias Shazam.ConfigSync

  @moduletag :config_sync_status

  setup do
    tmp = Path.join(System.tmp_dir!(), "shazam_sync_status_#{System.unique_integer([:positive])}")
    File.mkdir_p!(tmp)
    on_exit(fn -> File.rm_rf!(tmp) end)
    %{workspace: tmp}
  end

  describe "status/1" do
    test "returns empty status for fresh workspace", %{workspace: ws} do
      result = ConfigSync.status(ws)
      assert result.workspace == ws
      assert result.synced_files == []
      assert result.count == 0
      assert result.last_sync == nil
    end

    test "detects CLAUDE.md when present", %{workspace: ws} do
      File.write!(Path.join(ws, "CLAUDE.md"), "# Claude config")

      result = ConfigSync.status(ws)
      assert result.count >= 1
      assert Enum.any?(result.synced_files, fn f -> f.path == "CLAUDE.md" end)
      assert result.last_sync != nil
    end

    test "detects GEMINI.md when present", %{workspace: ws} do
      File.write!(Path.join(ws, "GEMINI.md"), "# Gemini config")

      result = ConfigSync.status(ws)
      assert Enum.any?(result.synced_files, fn f -> f.path == "GEMINI.md" end)
    end

    test "detects AGENTS.md when present", %{workspace: ws} do
      File.write!(Path.join(ws, "AGENTS.md"), "# Codex config")

      result = ConfigSync.status(ws)
      assert Enum.any?(result.synced_files, fn f -> f.path == "AGENTS.md" end)
    end

    test "detects claude agents directory", %{workspace: ws} do
      File.mkdir_p!(Path.join(ws, ".claude/agents"))

      result = ConfigSync.status(ws)
      assert Enum.any?(result.synced_files, fn f -> f.path == ".claude/agents" end)
    end
  end

  describe "header/0" do
    test "returns the auto-generated header string" do
      header = ConfigSync.header()
      assert is_binary(header)
      assert header =~ "Generated by Shazam"
      assert header =~ "Do not edit manually"
    end
  end

  describe "read_memories/1" do
    test "returns empty memories for fresh workspace", %{workspace: ws} do
      memories = ConfigSync.read_memories(ws)
      assert memories.project == []
      assert memories.rules == []
      assert memories.decisions == []
      assert memories.agents == %{}
    end

    test "reads project memories", %{workspace: ws} do
      dir = Path.join(ws, ".shazam/memories/project")
      File.mkdir_p!(dir)
      File.write!(Path.join(dir, "architecture.md"), "---\ntitle: Arch\n---\nUse microservices.")

      memories = ConfigSync.read_memories(ws)
      assert length(memories.project) == 1
      [mem] = memories.project
      assert mem.name == "architecture"
      assert mem.content =~ "Use microservices"
    end

    test "reads agent-specific memories", %{workspace: ws} do
      dir = Path.join(ws, ".shazam/memories/agents")
      File.mkdir_p!(dir)
      File.write!(Path.join(dir, "dev1.md"), "Prefers functional style.")

      memories = ConfigSync.read_memories(ws)
      assert memories.agents["dev1"] =~ "functional style"
    end

    test "skips SKILL.md files", %{workspace: ws} do
      dir = Path.join(ws, ".shazam/memories/rules")
      File.mkdir_p!(dir)
      File.write!(Path.join(dir, "SKILL.md"), "This should be skipped")
      File.write!(Path.join(dir, "coding.md"), "Use descriptive names")

      memories = ConfigSync.read_memories(ws)
      assert length(memories.rules) == 1
      assert hd(memories.rules).name == "coding"
    end
  end
end
